### ISSUE TITLE
Rethink loses all data on restart.

### ISSUE THREAD

**Issue by alanrme** [eslachance/enmap-rethink#7]
So I was trying to use Enmap Rethink for a Discord bot. All was going well, easy conversion from Mongo. But there was one problem, which you can see from the title. When I restarted the bot on Linux (mentioning that since it may be a linux issue?) the DB was empty. The bot found out that the guild info wasn't saved, and reset it to default. Why does it empty on restart?

**Comment by eslachance** [comment]
Note that in order to use any provider, you will need to make sure you're on Enmap version 3. Version 4 does not support enmap or mongo, and has different ways to start - if you try to use V3 code in V4, it will not save. 

Do `npm i eslachance/enmap#v3` to stay on the V3 branch.

**Comment by ProCreeper2000** [comment]
Thanks.

**Comment by alanrme** [comment]
It doesn't seem to work,
![image](https://user-images.githubusercontent.com/19237297/45556400-3457e180-b84c-11e8-9796-3f09404fc3ed.png)
Here's the image of the errors.

**Comment by alanrme** [comment]
Nevermind, I had to install git. But now the error is this, and i can't read from DB.
![image](https://user-images.githubusercontent.com/19237297/45557964-d88f5780-b84f-11e8-8a13-441e16f1fb96.png)
It always restarts when I try to read from DB with a bunch more errors

**Comment by eslachance** [comment]
This is indicating that it's failing to connect to Rethink. Check that it's actually running, and that you have the correct connection details.

**Comment by alanrme** [comment]
I don't know how to check that... should I change this part in the code?

`const Enmap = require('enmap');`

**Comment by eslachance** [comment]
No, this is related to your configuration when you create the provider code, as described here: 
https://github.com/eslachance/enmap-rethink#options

**Comment by alanrme** [comment]
Oh... how would I get the correct connection details? I'll try setting v4 defaults since it connected on that.

**Comment by alanrme** [comment]
Nope, it doesn't work.
Sorry if I'm terrible at this, I'm new to rethink and still learning node.

**Comment by eslachance** [comment]
You're missing a closing }) here, the one that closes the new Enmap.

**Comment by alanrme** [comment]
Shit i'm an idiot. Fixed, but still no dice.

**Comment by eslachance** [comment]
Please join https://discord.gg/4NE4bk7 and we'll figure this out together.

**Comment by alanrme** [comment]
alright thanks
