### ISSUE TITLE
All users have the same data

### ISSUE THREAD

**Issue by Azkun** [eslachance/enmap-rethink#8]
Hello, the issue description is in 2 language, the first, very well explained (in French) but the 2nd, done with google translation :(

1 in French : 
Bonjour, j'ai  un problème avec enmap, je stock la donnée comme ceci : 
  EnmapMoney.math("number", "add", 100); 
(Ceci est un exemple !) Mais, le problème est que ça stocke la donnée pour tout les utilisateurs, je veux que ça stocke que pour l'author (c'est un bot discord !)
Et, c'est qu'il n'y a aucune explication que j'ai trouvé dans la documentation :/ voilà pourquoi j'ai besoin d'aide !

Merci d'avance 👍 !

2 in English : 

Hello, I have a problem with enmap, I store the data like this:
   EnmapMoney.math ("number", "add", 100);
(This is an example!) But, the problem is that it stores the data for all users, I want it to store only for the author (it's a bot discord!)
And, there is no explanation that I found in the documentation: / that's why I need help!

Thanks in advance 👍!

**Comment by eslachance** [comment]
> issue is being handled on Discord already, please don't cross-post to github.
